create database Services
use services
CREATE TABLE  "AGENTS" 
   (	
    "AGENT_CODE" CHAR(6) NOT NULL PRIMARY KEY, 
	"AGENT_NAME" CHAR(40), 
	"WORKING_AREA" CHAR(35), 
	"COMMISSION" numeric(10,2), 
	"PHONE_NO" CHAR(15), 
	"COUNTRY" VARCHAR(25) 
	 );
CREATE TABLE  "CUSTOMER" 
   (	"CUST_CODE" VARCHAR(6) NOT NULL PRIMARY KEY, 
	"CUST_NAME" VARCHAR(40) NOT NULL, 
	"CUST_CITY" CHAR(35), 
	"WORKING_AREA" VARCHAR(35) NOT NULL, 
	"CUST_COUNTRY" VARCHAR(20) NOT NULL, 
	"GRADE" NUMERIC, 
	"OPENING_AMT" NUMERIC(12,2) NOT NULL, 
	"RECEIVE_AMT" NUMERIC(12,2) NOT NULL, 
	"PAYMENT_AMT" NUMERIC(12,2) NOT NULL, 
	"OUTSTANDING_AMT" NUMERIC(12,2) NOT NULL, 
	"PHONE_NO" VARCHAR(17) NOT NULL, 
	"AGENT_CODE" CHAR(6) NOT NULL REFERENCES AGENTS
);  
CREATE TABLE  "ORDERS" 
   (
        "ORD_NUM" NUMERIC(6,0) NOT NULL PRIMARY KEY, 
		"ORD_AMOUNT" NUMERIC(12,2) NOT NULL, 
		"ADVANCE_AMOUNT" NUMERIC(12,2) NOT NULL, 
		"ORD_DATE" DATE NOT NULL, 
		"CUST_CODE" VARCHAR(6) NOT NULL REFERENCES CUSTOMER, 
		"AGENT_CODE" CHAR(6) NOT NULL REFERENCES AGENTS, 
		"ORD_DESCRIPTION" VARCHAR(60) NOT NULL
   );

